sudo: false
language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer -V
  - composer require --dev friendsofphp/php-cs-fixer

script:
    - find . -path ./vendor -prune -o -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - if [ -z "${TRAVIS_COMMIT_RANGE}" ]; then CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT}"); else CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}"); fi
    - if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then IFS=$'\n' EXTRA_ARGS=('--path-mode=intersection' '--' ${CHANGED_FILES[@]}); fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no "${EXTRA_ARGS[@]}"; fi
